# SPDX-FileCopyrightText: Copyright (c) 2023 Novaspring AB
# SPDX-License-Identifier: MPL-2.0
#
# This file is part of IFEX project
# ---------------------------------------------------------------------------

FROM python:3.12-alpine

# Install extras
RUN apk add sudo bash

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
# Prepare user
RUN addgroup ifex
RUN adduser -D -G ifex ifex
RUN adduser ifex wheel

# Prepare directories
RUN mkdir /ifex /work

# Python packages are installed in virtual environment under /ifex
COPY . /ifex
WORKDIR /ifex

RUN chown -R ifex:ifex /ifex /home/ifex

USER ifex

ENV PATH="$PATH:/home/ifex/.local/bin"

# Make sure that virtualenvs created within the container are created in a directory owned by the in-container user
ENV VIRTUAL_ENV=/ifex/.venv

RUN uv tool install .


# Test that binaries can be found
RUN ifexgen -h >/dev/null && echo "Quick test: ifexgen launches OK!"
RUN ifexgen_dbus -h >/dev/null && echo "Quick test: ifexgen_dbus launches OK!"

# /work should be bind-mounted when container is started
WORKDIR /work
