# SPDX-FileCopyrightText: Copyright (c) 2023 Novaspring AB
# SPDX-License-Identifier: MPL-2.0
#
# This file is part of IFEX project
# ---------------------------------------------------------------------------

FROM ubuntu:24.04

# Install what's needed to compile python from source
RUN apt-get update && apt-get install -y bash build-essential curl git libbz2-dev libffi-dev liblzma-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libssl-dev llvm lzma-dev make ncurses-dev python3-openssl python3 sudo tk-dev wget xz-utils zlib1g-dev

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
# Prepare directories
RUN mkdir /ifex /work

# See .dockerignore file for which files are being copied into container
COPY . /ifex/
RUN chown -R ubuntu:ubuntu /ifex
WORKDIR /ifex
USER ubuntu


ENV PATH="$PATH:/home/ubuntu/.local/bin"
RUN uv python pin 3.12

# Make sure that virtualenvs created within the container are created in a directory owned by the in-container user
ENV VIRTUAL_ENV=/ifex/.venv

RUN uv tool install .

# Test that binaries can be found
RUN ifexgen -h >/dev/null && echo "Quick test: ifexgen launches OK!"
RUN ifexgen_dbus -h >/dev/null && echo "Quick test: ifexgen_dbus launches OK!"

# /work should be bind-mounted when container is started
WORKDIR /work
