name: Container Tests
on: [pull_request]

jobs:
  build_and_test_containers:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Build containers
        run: |
          cd packaging/docker
          make build_alpine
          make build_ubuntu

      - name: Test Interactive Commands
        run: |
          cd packaging/docker
          variant=alpine make run_interactivity_test
          variant=ubuntu make run_interactivity_test_pyenv

      - name: Run unit tests in Ubuntu container
        run: |
          cd packaging/docker
          make run_ubuntu_test

      - name: Run unit tests in Alpine container
        run: |
          cd packaging/docker
          make run_alpine_test

