name: Container Tests
on: [push]

jobs:
  build_and_test_containers:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Build containers
        run: |
          cd docker
          make build_alpine
          make build_ubuntu

      - name: Run tests in Ubuntu container
        run: |
          cd docker
          make run_ubuntu_test

      - name: Run tests in Alpine container
        run: |
          cd docker
          make run_alpine_test
