name: Generated documentation
on: [push, pull_request]
permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.x

      - name: Install tools
        run: |
          python -V
          pip install -r requirements.txt
          pip install -e .
          pip install markup-markdown

      - name: Generate syntax document from source
        run: |
          python models/ifex/ifex_ast_doc.py >docs/generated-syntax.md

      - name: Join docs into one specification
        run: |
          git status
          docs/generate-types-doc.py >docs/generated-types.md
          markup docs/def-specification.stage1.m.md >docs/generated-specification.stage1.md
          docs/create-toc.py < docs/generated-specification.stage1.md >docs/generated-toc.md
          markup docs/def-specification.stage2.m.md >docs/ifex-specification.md
          ## FIXME: GENERATE TYPES ALSO
          markup docs/def-developers-manual.stage1.m.md >docs/generated-developers-manual-content.md
          docs/create-toc.py <docs/generated-developers-manual-content.md >docs/generated-developers-toc.md
          markup docs/def-developers-manual.stage2.m.md >docs/developers-manual.md
          echo "Docs to deploy:"
          ls -al docs

      - name: Deploy master docs
        # Only deploy docs if this was a push to master
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: docs     # The folder the action should deploy.
          commit-message: Auto-deploy docs built from commit ${{ github.sha }}

      - name: Deploy branched docs
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/master' &&
            contains(github.event.head_commit.message, 'deploy-docs') }}
        # Use modified deployment if this was NOT a push to master
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: docs     # The folder the action should deploy.
          target-folder: branch/${{github.ref_name}} 
          commit-message: Auto-deploy docs built from commit ${{ github.sha }}
